[package]
name = "extract_state_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
lazy_static = "1.4.0"
clap = { version = "4.1.1", features = ["derive"] }
anyhow = "1.0.68"
